name: Product Deploy Trigger

on:
  repository_dispatch:
    types: [trigger-product]

jobs:
  # This job reads the product and outputs it so other jobs can use
  init:
    runs-on: ubuntu-latest
    outputs:
      product: ${{ github.event.client_payload.product }}
    steps:
      - name: Print selected product
        run: |
         echo "Selected product: ${{ github.event.client_payload.product }}"

  # Build job for Product A
  build_productA:
    needs: init
    if: needs.init.outputs.product == 'productA'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Product A
        run: |
          echo "Building Product A..."
          

  # Test job for Product A
  test_productA:
    needs: build_productA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Product A
        run: |
          echo "Running tests for Product A..."
          

  # Deploy job for Product A
  deploy_productA:
    needs: test_productA
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Product A
        run: |
          echo "Deploying Product A..."
          
  # Build job for Product B
  build_productB:
    needs: init
    if: needs.init.outputs.product == 'productB'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Product B
        run: |
          echo "Building Product B..."
          
  # Test job for Product B
  test_productB:
    needs: build_productB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Product B
        run: |
          echo "Running tests for Product B..."
          
  # Deploy job for Product B
  deploy_productB:
    needs: test_productB
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Product B
        run: |
          echo "Deploying Product B..."
          
  # Build job for Product C
  build_productC:
    needs: init
    if: needs.init.outputs.product == 'productC'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Product C
        run: |
          echo "Building Product C..."
          
  # Test job for Product C
  test_productC:
    needs: build_productC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Product C
        run: |
          echo "Running tests for Product C..."
          
  # Deploy job for Product C
  deploy_productC:
    needs: test_productC
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Product C
        run: |
          echo "Deploying Product C..."